CREATE TABLE IF NOT EXISTS public.orders (
  id text PRIMARY KEY,
  created_at timestamptz NOT NULL,
  short_ref text,
  email text,
  customer_email text,
  name text,
  phone text,
  shoe_type text,
  services jsonb,
  upgrades jsonb,
  delivery text,
  address_line1 text,
  city text,
  postcode text,
  preferred_date_time text,
  payment_mode text,
  payment_status text,
  amount_total integer,
  currency text,
  checkout_url text,
  mode text,
  stripe_customer_id text,
  stripe_subscription_id text,
  sendcloud_status text,
  sendcloud_status_updated_at timestamptz,
  sendcloud_status_history jsonb,
  shipping_label_id integer,
  tracking_number text,
  tracking_url text,
  abandoned_stage integer,
  abandoned_first_at timestamptz,
  abandoned_last_at timestamptz
);